---
title: "[Read me] application documentation"
output: html_notebook
---

### Team:
- Gaël CHARLES
- Corentin COSTE
- Ismail ZMERLI

This notebook is the documentation of the shiny app our team provided.  
This app is a dashboard that shows various information on trains and flights datasets. The files are quite large and yet can't be loaded into shiny directly.  
  
Consequently, we wrote a script that creates lighter aggregated dataframes. These are the dataframes we load into shiny.  
  
One can run this script if the corresponding datasets are found inside their respective folders in a "data" folder, at the root of the project, like so:

- server.R
- ui.R
- **data**
    - **french-sncf-trains-regularities**
        - full_trains.csv
        - regularite-mensuelle-tgv-aqst.csv
    - **usa-flights-delays**
        - airlines.csv
        - airports.csv
        - flights.csv

```{r}
# Run this cell to execute the script
source('create_aggregated_CSVs.R')
```

The app can now be used.
There are two tabs: one for controlling french trains aggregations, one for controlling USA flights aggregations.
In the trains dashboard, aggregations are grouped into three categories:
  
**Total aggregations**:  
These contain aggregations that plot the total number of something. We find here the number of trains carried out, canceled, late at departure, and late at arrival.
  
**Average aggregations**:  
These contain aggregations that plot the average number of something. We find here 6 plots: the average number of delayed trains at departure (or on arrival), and the average delay at departure (or on arrival) of all trains (or of late trains).
  
**Proportion aggregations**:  
These contain aggregations that plot some proportions (%). We find here the proportion of canceled trains, and the proportion of delay causes.

Every aggregation just mentioned can be shown aggregated per year regarding a specific station (or all stations), or per station.